# Site
repository: sproogen/resume-theme
favicon: images/favicon_1.ico

# Personal info
name: Dhrumil Patel
title: Data Science and Analytics
email: dhrumilpatel02@gmail.com
phone: +1 519 697 7110

# Social links
github_username: dhrumilpatel02
linkedin_username: dhrumilpatel02

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an experienced Data Science and Analytics Professional and have worked with startups building analytics dashboards to help investors, and clients invest in the right ventures, building and presenting reports to the stakeholders, maintaining the data quality. I've also briefly worked in the recruitment industry analyzing the trends in the US recruitment space. Currently, I am working to maximize the success rate of new products as well as minimize its risk at BMO Financial Group.

  Skills: <mark>SQL</mark>, <mark>Python</mark>, <mark>Tableau</mark>, <mark>Looker</mark>, <mark>Google Analytics</mark>, <mark>PowerBI</mark>, <mark>SAS</mark>

# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
more_title: Professional Certifications
more_content: | # this will include new lines to allow paragraphs
   - [Google Data Analytics Certification](https://www.coursera.org/account/accomplishments/specialization/certificate/JA2BG8UWMJ8Q) (Google)
   - [Google Analytics Individual Certification](https://skillshop.exceedlms.com/student/award/JYpnG5YLLQX7NgRncKNq2aor) (Google)
   - [Deep Learning](https://www.coursera.org/account/accomplishments/specialization/9RAPG5LSHANJ) (deeplearning.ai)
   - [SQL for Data Science](https://www.coursera.org/account/accomplishments/certificate/4QMWCBK3GE72) (University of California, Davis)
   - [SAS Certified Base Programmer for SAS 9](https://drive.google.com/file/d/1NZ6SBfoA6s20u6ZoV2yWDtZS-IRCZLkm/view?usp=sharing) (SAS Institute)
   - [SAS Certified Advanced Programmer for SAS 9](https://drive.google.com/file/d/1SKmbsttBl6VK_jvnPDfcPP2qv-8yzl-j/view?usp=sharing) (SAS Institute)
   - [Data Science Professional Certificate](https://www.coursera.org/account/accomplishments/specialization/certificate/LZBB5PRD6YMQ) (IBM)
   - [Data Visualization and Communication with Tableau](https://www.coursera.org/account/accomplishments/certificate/GWHTZFF7SNKJ) (Duke University)
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
